name: Marp to PDF
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Marp Build
      uses: docker://marpteam/marp-cli:latest
      with:
        args: "markdown/*.md -o ./ --allow-local-files"
      env:
        MARP_USER: root:root
    - name: Debug Output
      run: ls -la
    - uses: actions/upload-artifact@v4
      with:
        name: slides
        path: ./*.pdf
