name: Marp to PDF
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Marp Build
      run: |
        for file in markdown/*.md; do
          filename=$(basename "$file" .md)
          docker run --rm -v "$(pwd):/workspace" marpteam/marp-cli:latest "/workspace/$file" -o "/workspace/${filename}.pdf" --allow-local-files
        done
    - name: Debug Output
      run: ls -la
    - uses: actions/upload-artifact@v4
      with:
        name: slides
        path: ./*.pdf
