name: Marp to PDF
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: marpteam/marp-cli:latest
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - name: Create Output Directory
        run: mkdir -p /github/workspace/output && chmod -R 777 /github/workspace/output
      - name: Marp Build
        run: marp markdown/*.md -o /github/workspace/output --allow-local-files
      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: slides
          path: ./output/*.pdf

