name: Marp to PDF
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Output Directory
        run: mkdir -p output
      - name: Marp Build
        run: |
          for file in markdown/*.md; do
            filename=$(basename "$file" .md)
            docker run --rm -v "$(pwd):/workspace" marpteam/marp-cli:latest "/workspace/$file" -o "/workspace/output/${filename}.pdf" --allow-local-files
          done
      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: slides
          path: output/*.pdf


